apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
    cours: learn.garkado.com
  name: myapp
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: myapp
